### ISSUE TITLE
Ordering problem

### ISSUE THREAD

**Issue by twsiyuan** [golangtw/GolangTaiwanGathering#16]
Hi, 有考慮調整 Golang Taiwan Gathering 項目順序嗎？
最新的排在越上頭，不用特地拉到畫面底部去瀏覽最新活動的記錄，這樣比較方便。
此外更新時也比較容易吧，尤其是當 Gathering 記錄越來越多場時…

**Comment by kkdai** [comment]
Ok. 歡迎送 PR
