### ISSUE TITLE
GTG25 information update

### ISSUE THREAD

**Issue by kkdai** [golangtw/GolangTaiwanGathering#18]
https://golang.kktix.cc/events/gtg25

**Comment by neighborhood999** [comment]
- [Introduction to Grumpy](https://speakerdeck.com/m157q/20170718-gtg25-introduction-to-grumpy-1)
- Lighting Talk: [HUGO 靜態網站生成器 2 分鐘上手](https://t.co/JhUs0ElHVu)

**Comment by appleboy** [comment]
看起來應該改好了。
